services:
  testrunner:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    environment:
      LOCALSTACK: 1
      CI_DOCKER: 1
      ENV: local
      DEBUG: 1
      POSTGRES_URI: postgres://admin:password@postgres:5432/mydatabase
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
    depends_on:
      - localstack
      - postgres

  # LocalStack service
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack gateway
      - "4575:4575" # SNS service
      - "4576:4576" # SQS service
    environment:
      - SERVICES=s3,sns,sqs,sts
      - DEBUG=1
      - DEFAULT_REGION=eu-west-3
    volumes:
      - ./localstack:/var/lib/localstack

  # Postgres database service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  consumer:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    env_file:
      - .env.localstack
    depends_on:
      - localstack
      - postgres
    ports:
      - "8000:8000"
    command: ["uv", "run", "gunicorn", "src.main:app", "--bind", "0.0.0.0:8000", "--threads", "4"]

volumes:
  postgres_data:
